tasks:
  - init: echo "Replace me with a build script for the project."
    command: cd photo_stream_backing && bundle install && bundle exec jekyll build && mv -f ./_site/* ../ && git commit -a -m "regenerating jekyll site" && git push origin master
image:
  file: .gitpod.Dockerfile
