name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install libvips
      run: sudo apt-get update && sudo apt-get install libvips-dev libglib2.0-0
    - name: vips
      run:  wget -O- https://github.com/libvips/libvips/releases/download/v8.8.3/vips-8.8.3.tar.gz | tar xzC /tmp && cd /tmp/vips-8.8.3 \
            && ./configure --prefix=/usr --disable-static --disable-debug \
            && make V=0 \
            && make install \
            && gem install ruby-vips
            
    - name: Bundle update in the builder container
      run:
      |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll/Gemfile.lock && bundle update --full-index"

    - name: Build the site in the jekyll/builder container
      run:
      |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
