name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: vips
      run:  cd /tmp && wget https://github.com/libvips/libvips/releases/download/v8.8.3/vips-8.8.3.tar.gz 
    - name: vips2
      run:
            cd /tmp && tar -xvzf vips-8.8.3.tar.gz 
    - name: vips3
      run:
            sudo mkdir /usr/include/vips
            && sudo chmod 777 /usr/include/vips
            && cd /tmp/vips-8.8.3 
            && ./configure --prefix=/usr --disable-static --disable-debug 
            && make V=0 
            && sudo make install 
    - name: vips4
      run:            
            gem install ruby-vips
            
    - name: Bundle update in the builder container
      run:
      |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll/Gemfile.lock && bundle update --full-index"

    - name: Build the site in the jekyll/builder container
      run:
      |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
